/* Project settings */
var hmAnimate = false;
var hmPopupSticky = true;
var hmImageLightbox = false;
var hmVideoLightbox = false;
var hmLightboxConstrained = true;
var hmForceRedirect = false;
var hmTocSingleClick = false;
var autocollapse = false;
var gaaccount = "";
var initialtocstate = "collapsed";
